### ISSUE TITLE
Slow in processing files

### ISSUE THREAD

**Issue by bsddemon** [cwi-swat/clair#13]
On average CDT takes 8 seconds and ClaiR 2 seconds to process a "common"/not that huge source file. Can the processing time be improved?

**Comment by rodinaarssen** [comment]
There is little I can do about the time it takes CDT to parse a file. Since ClaiR has to marshall the full AST, it needs to traverse and build the full AST, also leaving little opportunity for speed-ups. I'll have a look whether there is some unnecessary (or no longer needed) functionality that I can prune, but I would only expect marginal improvements, if any.

**Comment by bsddemon** [comment]
Is it e.g. faster to process all files in a directory in one go instead of processing separately?

**Comment by rodinaarssen** [comment]
Generating a file that includes a set of files (e.g., a file that consists of just `include` directives) leads to a significant speed-up compared to processing each file separately; however, the results may be different/incorrect due to, e.g., defined macros, defined typedefs, parse errors due to double forward declarations.

**Comment by rodinaarssen** [comment]
I removed some legacy fragments from ClaiR and moved things around internally a bit. My anecdotal evidence suggests that for a single (large) file, CDT parsing time has been marginally reduced, and marshalling time was reduced significantly.

**Comment by rodinaarssen** [comment]
Closing this for now.
