### ISSUE TITLE
Cannot import module

### ISSUE THREAD

**Issue by MarieNyst** [cwi-swat/clair#9]
Hi,

I'm trying to use ClaiR but am unable to import the module.
When doing `import lang::cpp::AST;`
I get the following error :
`Could not import module lang::cpp::AST: can not find in search path`
Even if the clair module is installed, it seems that the language is not in the path.

I soft linked the `rascalmpl/eclipse/library/lang/cpp` to `src/lang/cpp` folder and now run into an other error :
`Cannot link method lang.cpp.internal.Parser because: class not found`

. arch linux
. eclipse 2019-06
. rascal 0.15.0 (unstable, because the stable didn't install due to library version conflicts)

**Comment by jurgenvinju** [comment]
thanks for reporting. we're currently trying to release a stable rascal version. the first was yesterday and then we always have some minor issues while "stabilizing the stable".

the softlink method won't work due to all kinds of classpath stuff. I'll let you know here when it works again. CC: @DavyLandman @rodinaarssen

**Comment by DavyLandman** [comment]
could you try again with a fresh eclipse and a fresh install of stable? We've been working on getting a more stable version of stable.

**Comment by MarieNyst** [comment]
I tried and it works now, thank you :)
